# Generated by Django 2.2.5 on 2020-04-23 03:59

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CustomerID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('pin', models.CharField(max_length=6)),
                ('poc', models.CharField(max_length=20, verbose_name='point of contact(name)')),
                ('contact', phone_field.models.PhoneField(help_text='phone number of the company or poc', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='modules',
            fields=[
                ('designID', models.CharField(default='000', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='aaaa', max_length=20)),
                ('Type', models.CharField(default='aaaa', max_length=10)),
                ('made', models.DateField(auto_now=True)),
                ('inventory', models.IntegerField(default=111)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('placed', models.DateTimeField(auto_now=True)),
                ('due', models.IntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bon.customer')),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendorID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('poc', models.CharField(max_length=20, verbose_name='Point of contact(name)')),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('city', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='sub_module_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('designID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Module', to='bon.modules')),
                ('subID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Module', to='bon.modules')),
            ],
        ),
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bon.orders')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bon.modules')),
            ],
        ),
        migrations.CreateModel(
            name='parts',
            fields=[
                ('PartID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('partType', models.CharField(max_length=10)),
                ('weight', models.FloatField(verbose_name='Weight(in grams)')),
                ('height', models.FloatField(verbose_name='Height(in cm)')),
                ('width', models.FloatField(verbose_name='Width(in cm')),
                ('length', models.FloatField(verbose_name='Length(in cm')),
                ('cost', models.IntegerField(verbose_name='Cost(in rupees')),
                ('vendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bon.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='part_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('PartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bon.parts')),
                ('designID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bon.modules')),
            ],
        ),
    ]
