# Generated by Django 2.2.5 on 2020-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='assembly_fee',
            field=models.IntegerField(default=0, verbose_name='per_piece_assembly_fee(in rupees'),
        ),
        migrations.AddField(
            model_name='modules',
            name='design_fee',
            field=models.IntegerField(default=0, verbose_name='design_fee(in rupees)'),
        ),
    ]
