# Generated by Django 2.2.5 on 2020-04-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon', '0002_auto_20200424_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='modules',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='media/parts'),
        ),
        migrations.AddField(
            model_name='parts',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='media/parts'),
        ),
    ]
