# Generated by Django 2.2.5 on 2020-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon', '0005_auto_20200425_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='Sub_modules',
            field=models.IntegerField(default=0, verbose_name='Number of modules'),
        ),
        migrations.AddField(
            model_name='modules',
            name='parts',
            field=models.IntegerField(default=0, verbose_name='Number of parts'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
