# Generated by Django 2.2.5 on 2020-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon', '0006_auto_20200425_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='Total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
