# Generated by Django 2.2.5 on 2020-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon', '0010_auto_20200505_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
