# Generated by Django 2.2.5 on 2020-05-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon', '0011_orders_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='media/modules'),
        ),
    ]
